# Generated by Django 5.1.7 on 2025-03-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
