# Generated by Django 4.2.7 on 2025-03-21 16:55

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantreview',
            name='rating',
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='cleanliness_rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='環境衛生'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='delivery_service',
            field=models.CharField(choices=[('yes', '有提供外送'), ('no', '無提供外送')], default='no', max_length=3, verbose_name='外送服務'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='dine_in_space',
            field=models.CharField(choices=[('yes', '有內用空間'), ('no', '無內用空間')], default='yes', max_length=3, verbose_name='內用空間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='electronic_menu',
            field=models.CharField(choices=[('yes', '有電子菜單'), ('no', '無電子菜單')], default='no', max_length=3, verbose_name='電子菜單'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='food_type',
            field=models.CharField(default='中式料理', max_length=255, verbose_name='美食種類'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='is_google_maps_verified',
            field=models.BooleanField(default=False, verbose_name='Google Maps 驗證'),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='multiple_payment',
            field=models.CharField(choices=[('yes', '有多元支付'), ('no', '無多元支付')], default='no', max_length=3, verbose_name='多元支付'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='preorder_app',
            field=models.CharField(choices=[('yes', '有預點APP'), ('no', '無預點APP')], default='no', max_length=3, verbose_name='預點APP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='service_rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='服務態度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='speed_rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='出餐速度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='taste_rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='餐點風味'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='address',
            field=models.TextField(verbose_name='餐廳地址'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='restaurant_name',
            field=models.CharField(max_length=255, verbose_name='餐廳名稱'),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='review',
            field=models.TextField(verbose_name='評論內容'),
        ),
    ]
