# Generated by Django 4.2.7 on 2025-03-21 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0002_auto_20250322_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterModelOptions(
            name='restaurantreview',
            options={'ordering': ['-created_at'], 'verbose_name': '美食評論', 'verbose_name_plural': '美食評論'},
        ),
    ]
